{% set name = "xyzspaces" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/heremaps/xyz-spaces-python/archive/{{ version }}.tar.gz
  sha256: 0a0a05729daa38e9e7dc09f16ac43f4cf220ff1fe13424c6a6edea0b97db8b2d

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - geobuf
    - turfpy >=0.0.3
    - fiona
    - geojson
    - geopandas
    - requests
    - ijson ==3.1.1
    - backoff >=1.10.0

test:
  imports:
    - xyzspaces

about:
  home: https://github.com/heremaps/xyz-spaces-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Manage your XYZ Hub server or HERE Data Hub from Python.'

  description: |
    xyzspaces provides a programmatic interface to a XYZ Hub or HERE Data Hub
    <https://here.xyz> geospatial database and service for Python 3.6+. It is
    pure Python code with few core dependencies, but benefits from optional
    requirements when used in a typical Jupyter notebook context.
  doc_url: https://xyz-spaces-python.readthedocs.io/
  dev_url: https://github.com/heremaps/xyz-spaces-python

extra:
  recipe-maintainers:
    - deeplook
    - omanges
    - sackh
